### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by chocoelho**
- Update pyflakes support to < 2.1.0
- Add bandit support
- Ignore `__pycache__` and `node_modules`
- Fix compatibility issues with mypy >= 0.730
- Add support for Python 3.8

### CODE REVIEW

**Comment by chocoelho** [comment]
@rik @Dunedan please, check `1.2.0.dev3`

**Comment by rik** [comment]
Working well here!

**Comment by Dunedan** [comment]
There doesn't seem to be a `1.2.0.dev3` tag. The current status of `develop` works fine here as well though. :+1:

**Comment by rik** [comment]
https://pypi.org/project/prospector/1.2.0.dev3/

**Comment by Dunedan** [comment]
Thx. I wasn't aware this version is available on PyPI and was looking for a tag in the repo.

**Comment by chocoelho** [comment]
Yeah, I forgot to create the tag here for this dev release. Prioritized the dev releases on Pypi.

**Comment by rik** [comment]
Is there anything preventing releasing 1.2.0?

**Comment by chocoelho** [comment]
> Is there anything preventing releasing 1.2.0? (besides time from maintainers)

Mostly time, but I'm also giving some time for people to interact with this release. I think that by Friday we should have the final release.

**Pull request merged**
