### PR TITLE
Change restricted version of pyflakes

### LINKED ISSUE #307: Flake8 latest version now uses pyflakes 2.0.0, and breaks prospector,
When installing prospector with flake8 latest version, you have a warning :
```
prospector 1.1.6.2 has requirement pyflakes<2.0.0,>=0.8.1, but you'll have pyflakes 2.0.0 which is incompatible.

```
Flake8 now uses pyflakes 2.0.0
https://gitlab.com/pycqa/flake8/blob/master/setup.py#L25
and is restricted by prospector 
https://github.com/PyCQA/prospector/blob/8bb1970aa31b962291ef0cff4b757a34aa566298/setup.py#L29

Is it possible to be compatible with this new version?

Thanks a lot for your work

### PR DESCRIPTION
**Pull request by IDerr**
Change restricted version from 2.0.0 to 2.1.0 to fix #307

### CODE REVIEW

**Comment by Kilo59** [comment]
Would it be better (and possible) to loosen the requirements to allow for minor/micro updates to `pyflakes` while restricting major/minor ones?

Would either of these work?
```
'pyflakes<2.1,>=0.8.1',
```
```
'pyflakes<2,>=0.8.1',
```

**Comment by carlio** [comment]
Prospector has the problem that it is using apis of several other libraries with their own release cycles, and some of those apis are not designed to be public but rather internal, so it's very easy for any release of any upstream dependency to break prospector. That's why things have moved to being very restrictive, because broken prospector means broken builds for lots of people and ultimately the bug reports go here first. 

A better "notification -> update of prospector -> release" cycle is necessary unfortunately to avoid people spending their morning working out why builds suddenly break and then prospector devs have to work out why and then it turns out that pylint renamed a function or something...

**Comment by Kilo59** [comment]
I agree, it would be nice if only allowing micro-releases, for example, would guarantee and only ever fix minor bugs but I don't think that's something you could be sure of.

This is a nice new feature of github.
https://help.github.com/articles/watching-and-unwatching-releases-for-a-repository/

Perhaps it can be a part of that new release cycle. Even better if say a CI job could be kicked off and tested with the new pinned version automatically.

**Comment by Kilo59** [comment]
Should give this a try.
I set it up on one of my repos a little while ago and actually found it annoying so I turned it off.
But I think it might actually work very well for this problem.

It will automatically submit PR's with updated requirements files when a dependency gets updated.

https://pyup.io/

**Comment by changeling** [comment]
What's the status of this?

**Comment by IDerr** [comment]
Thanks for your work guys

**Comment by chocoelho** [comment]
Thanks @IDerr I hope to ship this soon, at least in a dev version.

**Pull request merged**
