### PR TITLE
Add mypy support

### LINKED ISSUE #198: Support mypy
[mypy](https://github.com/python/mypy) static checks source code for type (annotation) violations. The ouput is pretty similar to other tools, e.g.:

```
fs/csm/common/model.py: note: In member "__init__" of class "StrProxy":
fs/csm/common/model.py:24: error: The return type of "__init__" must be None
fs/csm/common/logic/bundle.py: note: In member "__init__" of class "Bundle":
fs/csm/common/logic/bundle.py:8: error: The return type of "__init__" must be None
fs/csm/__init__.py: note: At top level:
fs/csm/__init__.py:2: error: Cannot determine type of '__path__'
fs/__init__.py:2: error: Cannot determine type of '__path__'
```

Would be nice to control `mypy` through `prospector` as well (to get pylint-compatible output etc.).

### PR DESCRIPTION
**Pull request by chocoelho**
This PR resolves #198.

`mypy` doesn't output a code to identify the errors, it basically works with options you pass on the command line and the interface available to integrate with other tools accepts these arguments, so that's why it's not following the pattern of using `disable` messages but rather entries like `disallow`, `no-check` and so on. 

These are some screenshots of it working:

### Running only with mypy tool
image

image

### VS Code output
image

### .prospector.yaml configuration
image

### CODE REVIEW

**Comment by pmatos** [comment]
Is there a reason this hasn't been merged?

**Comment by chocoelho** [comment]
@pmatos I guess it wasn't reviewed yet

**Comment by chocoelho** [comment]
This PR is going to take a little while longer to be merged. After syncing with the `develop` branch, I'm going to write a few more tests just to make sure it's properly integrated. But we're back on business :)

**Comment by twidi** [comment]
If prospector runs flake8, with its plugins, then the flake8-mypy should be enough instead of adding mypy support directly in prospector.

**Comment by fabianbuechler** [comment]
@twidi flake8 operates on single files, while mypy analyzes a complete codebase. The flake8-mypy plugin is therefore somewhat limited. Basically this [note from the flake8-mypy](https://github.com/ambv/flake8-mypy#two-levels-of-type-checking) page says it all:

> Flake8 operates on unrelated files, it doesn’t perform full program analysis. In other words, it doesn’t follow imports. This is a curse and a blessing. We cannot find complex problems and the number of warnings we can safely show without risking false positives is lower. In return, we can provide useful warnings with great performance, usable for realtime editor integration.

**Comment by twidi** [comment]
Yes indeed, you're right.

**Comment by carlio** [comment]
Looks good to me.

**Pull request merged**
