### PR TITLE
Fix undefined name sre_constants in Python 3.11

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/PyCQA/prospector/issues/546#issuecomment-1336709154

@gopackgo90 Your review, please.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to the dependencies
- [ ] I have updated the dependencies accordingly
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
There's still a warning in 3.11:
```
tests/execution/test_execution.py::test_non_subpath
  module 'sre_constants' is deprecated
```

**Comment by cclauss** [comment]
Good catch.  Thanks.

**Comment by gopackgo90** [comment]
I'm a little surprised this works on Python < 3.11, because on my own system, doing this sort of import doesn't work for me on Python 3.8:

```
$ python
Python 3.8.13 (default, Aug 16 2022, 12:16:29) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re._constants
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 're._constants'; 're' is not a package
```

I had anticipated a fix would be to do conditional imports like either https://github.com/jwilk/pydiatra/commit/b69f3fcd1dfb7bda8b5e59d760d1dbe37eaae63d or https://github.com/The-Compiler/hypothesis/commit/66ca462ddc6426d35047508d95e660a77999197b.

**Comment by Pierre-Sassoulas** [comment]
The tests are green, but maybe this file isn't even imported ?

**Comment by cclauss** [comment]
Or the two exceptions are never triggered.

**Pull request merged**
