### PR TITLE
CI cache is keyed on a file that no longer exists

### PR DESCRIPTION
**Pull request by cclauss**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to the dependencies
- [ ] I have updated the dependencies accordingly
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
I have no ideas what the problem with bandit/vulture might be.

**Comment by cclauss** [comment]
https://github.com/PyCQA/prospector/actions/runs/3111097228/jobs/5042999721#step:6:230
> Warning: The file chosen for install of gitpython 3.1.20 (GitPython-3.1.20-py3-none-any.whl) is yanked. Reason for being yanked: Issues with typing of ordered dict

https://pypi.org/project/GitPython/#history scroll down to v3.1.20 in

**Comment by cclauss** [comment]
https://github.com/PyCQA/prospector/actions/runs/3111097228/jobs/5043012076#step:6:70
How, why are we removing bandit and vulture just before testing for their presence?

**Comment by cclauss** [comment]
I would just rip out all the cache logic and do poetry builds.

**Comment by cclauss** [comment]
This PR is safe to review and land.  It is a move in the right direction even if it does not solve the problem.

**Comment by cclauss** [comment]
After wasting still more time on this, it is vital to figure out the gitpython thing.  https://github.com/PyCQA/prospector/pull/520#issuecomment-1255897486

**Comment by carlio** [comment]
Hi there, I'm currently on holiday so won't have a chance to look into all the PRs and things for a little while. 

However feel free to ditch (or completely rewrite) the CI config, it was written a while ago and before even switching to poetry, I just left it as it worked - and I didn't write it so I didn't want to fiddle with it :-)

**Comment by cclauss** [comment]
Hi.  Please do enjoy your time off.

Thanks but I would need to learn Poetry which has not fit inside my head in past attempts.

**Comment by Pierre-Sassoulas** [comment]
I did the migration from travis to github actions, most of it is kept as it was before what is new was adapted from pylint and is not guaranteed to be coherent or optimized. I don't think it's necessary to migrate to poetry though. Worst case scenario the cache can be removed we have very few merge requests.

**Comment by cclauss** [comment]
Closing in favor of #522

**Pull request closed without merging**
