### PR TITLE
Add support pylint --load-plugins option in profile

### PR DESCRIPTION
**Pull request by SergeyKosarchuk**
This PR relates to #315.
This is simple way to load one tool specific option (load-plugins in pylint) from profile and use it. Any thoughts on how to use specific options in profile? Because for now I haven't found anything better.

### CODE REVIEW

**Comment by carlio** [comment]
Looks good to me! Any chance you could add some docs to the https://github.com/PyCQA/prospector/blob/master/docs/profiles.rst profiles page? Probably in this section - https://github.com/PyCQA/prospector/blob/master/docs/profiles.rst#tweaking-certain-aspects

**Comment by carlio** [comment]
Brilliant thanks!

**Comment by SergeyKosarchuk** [comment]
@carlio Always a pleasure!

**Comment by tpansino** [comment]
I'd like to use this feature, but it looks like it hasn't been released yet. Is that correct? Is there a reason the `develop` branch hasn't had a new release cut in the 5 months since this was merged?

**Pull request merged**
