### PR TITLE
Fix for pycodestyle not picking up modules in non-package dirs

### PR DESCRIPTION
**Pull request by hjoukl**
As reported in #179, the pycodestyle/pep8 tool fails to
- check Python files in the root PATH directory
- non-package directories in PATH
when driven by prospector.

See the comments to #179 for more discussion.

This PR takes the simple approach of using found_files.iter_module_paths() for explicit files
mode and rootpath for "single directory arg" mode (leaving file lookup to
pep8/pycodestyle) instead of  iter_package_paths(). 

Comes with extensive tests, also adding a bunch of tests for the general finder functionality.

Edit: PR looks intimidating now judging by the number of commits, but note that the actual changes to the 
prospector codebase are small - it's mostly test additions... ;-)

### CODE REVIEW

**Comment by hjoukl** [comment]
S.th. amiss with the code-quality/landscape results reporting? If I follow the Details link everything seems fine, even a slight "score increased" is shown.

**Comment by carlio** [comment]
Fantasic PR and report, thank you very much. I am finally getting to dealing with all the built-up problems so will check this out and merge soon.

**Comment by harrisont** [comment]
Looking forward to this fix. Anything blocking it from being merged?

**Comment by chocoelho** [comment]
I'm currently reviewing this PR, just FYI, hope to merge it soon.

**Comment by cclauss** [comment]
Please resolve conflicts.

**Comment by Pierre-Sassoulas** [comment]
I won't be able to okay this one it's too technical for me. Please be mindful of your time @hjoukl :)

**Comment by hjoukl** [comment]
Hi @carlio, @chocoelho, @Pierre-Sassoulas, happy to see this gain traction again.

Alas, this PR has become pretty rusty and at this point I'm unsure how it can be best brought up-to-date. For one I'm unsure if the initial problem reported in #179 persists(?), since https://github.com/PyCQA/prospector/commit/58f9486227ab88086217badd62c9d385baa72703#diff-e7bec612b6b0afbed5f7116cdb3147775c8262078970c4cddb6d5efe5c0258b7 made significant changes to relevant parts of the affected code.

Second, I noticed a big refactoring going on in the develop branch which looks like it makes rebasing quite hard, wrt the finder.py changes and tests.

So: What to base this upon in the 1st place - the head of the development branch?
Looks to me like I basically needed to cherry-pick and adapt the test additions (original PR consists mainly of test code), see if the problem is still provoked by the additional tests and then look how it could be fixed. Going down this route I would probably abandon this PR in favor of a new one. No promises, though ;-)

What d'ya think?

**Comment by Pierre-Sassoulas** [comment]
> What d'ya think?

 I'd at least try to rebase first before re-doing everything, but think you're the one who knows best 😄

**Comment by carlio** [comment]
@hjoukl I'd hold off on this for now, as I have a big fat branch with lots of changes including swapping to using `pathlib` for path-related things. I'll should create a draft PR for visibility, it's living on my own repo for now!

**Comment by hjoukl** [comment]
@carlio, @Pierre-Sassoulas Thanks for the infos - feel free to ping me when these `pathlib` changes have landed. I'd then try and add the adapted original tests.

**Comment by carlio** [comment]
@hjoukl The pathlib changes is now in the [develop branch](https://github.com/PyCQA/prospector/tree/develop)

I was able to reproduce your issue, and the new code does not appear to have that problem any more. Please do try it out and if you still have it let me know!

I've got a couple of other bugfixes I want to get in before I release this code as an RC.

**Comment by carlio** [comment]
A follow up, but version 1.8.0 rc0 is now on PyPI

**Comment by carlio** [comment]
I shall close this because I suspect it is fixed, at least my own tests say it is, but if you try again and find it doesn't work please re-open or create a new issue.

**Pull request closed without merging**
