### PR TITLE
Upgrade GitHub Actions

### PR DESCRIPTION
**Pull request by cclauss**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] My change requires a change to the dependencies
- [x] I have updated the dependencies accordingly
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
3.11 won't work because we need pylint to work with 3.11 first, and pylint need dill to work with 3.11 first.

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
Look like the cache version need to be upgraded (?)

**Comment by cclauss** [comment]
Same cache issue on the unrelated #519

**Comment by cclauss** [comment]
The cache logic was based on `setup.cfg` but this repo has abandoned that file in favor of `pyproject.toml`.

**Pull request closed without merging**
