### PR TITLE
Accept all new version of pyflakes 2

### PR DESCRIPTION
**Pull request by sbrunner**
## Description
Accept all new version of pyflakes 2

## Related Issue
#454

## How Has This Been Tested?
Just run the CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] My change requires a change to the dependencies
- [x] I have updated the dependencies accordingly
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Thank you for the MR, could you add a changelog please ? :)

**Comment by sbrunner** [comment]
@Pierre-Sassoulas done, does it look good?

**Review by Pierre-Sassoulas — APPROVED** [review]
LGTM, thank you. I think we can trust pyflake to not do breaking changes. I'll wait until 2022 to merge in order to see if there are other opinions on this :)

**Comment by sbrunner** [comment]
@Pierre-Sassoulas up :-)

**Comment by Pierre-Sassoulas** [comment]
We are indeed in 2022 !

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request merged**
