### PR TITLE
Support more kinds of mypy messages

### PR DESCRIPTION
**Pull request by rik**
Extracts a `format_message` to help unit testing

fix https://github.com/PyCQA/prospector/issues/339

### CODE REVIEW

**Comment by rik** [comment]
The `mypy` dependency is the reason the tests are failing. The tests don't use `mypy` at all but being in the same file, the import fails.

Some options:
- Move `import mypy` into `MypyTool.__init__`
- Move `format_message` into another file.
- Install `mypy` in test environments (and figure how to do it)

@chocoelho Do you have any preference on how to move forward here?

**Comment by chocoelho** [comment]
Can you point the PR to develop? We might still have chance to ship it in 1.1.7 and before that have a 1.1.7.dev1.

**Comment by rik** [comment]
That's done. Any opinion on how to pass tests?

**Comment by chocoelho** [comment]
@rik can you try updating .travis.yml install option to add mypy? Prob worth moving line 17 into 13 in this file and install only once.

**Comment by rik** [comment]
The 2.7 failure seems to be https://sourceforge.net/p/docutils/bugs/365/.

**Comment by chocoelho** [comment]
@carlio as Python 2 support is being handled in https://github.com/landscapeio/prospector2 and discussed in here https://github.com/PyCQA/prospector/issues/265, do you think it makes sense dropping it from TravisCI?

**Comment by rik** [comment]
So docutils has been fixed but the 2.7 build is still failing because `mypy` is not installed on 2.7 builds.

**Comment by carlio** [comment]
ahem "handled" I had largely ignored it :-)  but yes the idea was that prospector is py3 only as of that point and prospector2 will deal with anyone stuck using 2.

**Comment by chocoelho** [comment]
@rik there are two approaches we can take here:
1. check for the python version before the tests which could lead to a bunch of repeated code just to check this
2. implement a decorator that would behave as a `skipIf`, just like pytest does (IIRC, unittest does have a skip decorator of some sort but I'm not sure whether it would work for test classes or if nosetest would respect it)

**Comment by rik** [comment]
Thanks for maintaining this very useful tool!

**Comment by chocoelho** [comment]
You're welcome! We just published `1.1.7.dev1` with this fix, hope we release `1.1.7` soon.

**Pull request merged**
